language: php


notifications:
  email:
    on_success: never
    on_failure: change


services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

# Explicitly test against supported versions of PHP
#
# Reference: https://www.php.net/supported-versions.php
php:
  - 7.4
  - 7.3
  - 7.2


# Test against the latest version of WordPress and one version back.
env:
  - WP_VERSION=latest
  - WP_VERSION=5.3
  - WP_VERSION=5.2
  - WP_VERSION=5.1

# Customize the build matrix.
matrix:
  fast_finish: true
  exclude:
    - php: 7.4
      env: WP_VERSION=5.1
    - php: 7.4
      env: WP_VERSION=5.2
    - php: 7.4
      env: WP_VERSION=5.3

    # Run PHP_CodeSniffer
    - name: Coding standards
      php: 7.4
      env: WP_VERSION=latest


    # Nightly versions of PHP and WordPress.
    - name: Bleeding edge
      php: 7.4
      env: WP_VERSION=trunk

  # Jobs that are permitted to fail without breaking the build
  allow_failures:
    - name: Bleeding edge

before_install:
  - nvm install 'lts/*'
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || return 0

install:
  # Install our Composer dependencies
  - composer install --prefer-dist --no-interaction

  - npm ci --prefer-offline --progress=false

  # Install the WordPress core test suite
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - |
    # If we've set the $WP_TRAVISCI variable to run PHPCS, do that instead
    # of running PHPUnit.
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      ./vendor/bin/phpcs

    else
      # Execute the test suite
      ./vendor/bin/phpunit

      # Optionally run the tests again in a multisite environment
      #WP_MULTISITE=1 ./vendor/bin/phpunit
    fi
  - composer check-php
  - npm run lint:js:src
  - npm run build

